### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'en')

### ISSUE THREAD

**Issue by djclarkson** [marmooo/fontconv#1]
fontconv IxarText-Regular.woff2 IxarText-Regular.ttf
file:///Users/xxxx/.nvm/versions/node/v21.5.0/lib/node_modules/fontconv/esm/fontconv/mod.js:133
        styleName: font.names.fontSubfamily.en,

**Comment by marmooo** [comment]
It is clear from the code that an error occurs if the property does not exist,
but I would like to know under what conditions it does not exist.

I checked all the fonts in Google fonts, but it didn't reproduce.
In the reproduction test, I ran the following on Deno (not Node 21).
(1) .ttf --> .woff2
(2) .ttf --> .woff2 --> .ttf

Please attach the file with the problem.

**Comment by marmooo** [comment]
closed.

**Comment by marmooo** [comment]
closed.
